import type { GameDraft, PickupGame, SportName } from './types';

export const featuredSports: SportName[] = ['Soccer', 'Frisbee', 'Tennis'];

export type LocationInfo = {
  sports: SportName[];
  address: string;
  availability: 'anytime' | { [day: string]: { start: string; end: string } };
};

export const locations: { [key: string]: LocationInfo } = {
  'Hutchson Field': {
    sports: ['Soccer', 'Frisbee'],
    address: '2331 Campus Dr, Evanston, IL 60208',
    availability: {
      mon: { start: '18:00', end: '22:00' },
      tue: { start: '18:00', end: '22:00' },
      wed: { start: '18:00', end: '22:00' },
      thu: { start: '18:00', end: '22:00' },
      fri: { start: '18:00', end: '22:00' },
      sat: { start: '08:00', end: '21:00' },
      sun: { start: '08:00', end: '21:00' },
    },
  },
  'Deering Meadow': {
    sports: ['Frisbee'],
    address: '1917 Sheridan Rd, Evanston, IL 60208',
    availability: 'anytime',
  },
  'Northwestern Tennis Courts': {
    sports: ['Tennis'],
    address: '1847 Sheridan Rd, Evanston, IL 60208',
    availability: 'anytime',
  },
};

export const initialGames: PickupGame[] = [
  {
    id: '1',
    sport: 'Soccer',
    location: 'Hutchson Field',
    startTime: '2026-04-07T18:00',
    endTime: '2026-04-07T19:30',
    capacity: 14,
    organizer: 'maya@example.com',
    note: 'Small-sided game with quick rotations and plenty of subs.',
    skillLevel: 'Beginner',
    ageRange: '18+',
    gender: 'Mixed',
    requirements: 'Bring water and arrive a few minutes early.',
    players: [
      { name: 'Maya', email: 'maya@example.com' },
      { name: 'Jordan', email: 'jordan@example.com' },
      { name: 'Alex', email: 'alex@example.com' },
    ],
  },
  {
    id: '2',
    sport: 'Tennis',
    location: 'Northwestern Tennis Courts',
    startTime: '2026-04-07T19:00',
    endTime: '2026-04-07T20:00',
    capacity: 4,
    organizer: 'avery@example.com',
    note: 'Casual doubles match.',
    skillLevel: 'Intermediate',
    ageRange: '18+',
    gender: 'Mixed',
    requirements: 'Bring your own racket.',
    players: [
      { name: 'Avery', email: 'avery@example.com' },
      { name: 'Sam', email: 'sam@example.com' },
    ],
  },
  {
    id: '3',
    sport: 'Frisbee',
    location: 'Deering Meadow',
    startTime: '2026-04-08T10:00',
    endTime: '2026-04-08T11:30',
    capacity: 12,
    organizer: 'chris@example.com',
    note: 'Ultimate frisbee game - bring your own disc if you have one.',
    skillLevel: 'Intermediate',
    ageRange: '16+',
    gender: 'Mixed',
    requirements: 'Comfortable running shoes.',
    players: [
      { name: 'Chris', email: 'chris@example.com' },
      { name: 'Taylor', email: 'taylor@example.com' },
    ],
  },
  {
    id: '4',
    sport: 'Soccer',
    location: 'Hutchson Field',
    startTime: '2026-04-08T19:00',
    endTime: '2026-04-08T20:30',
    capacity: 16,
    organizer: 'diana@example.com',
    note: 'Competitive 11v11 match.',
    skillLevel: 'Advanced',
    ageRange: '18-35',
    gender: 'Mixed',
    requirements: 'Cleats required, shin guards recommended.',
    players: [
      { name: 'Diana', email: 'diana@example.com' },
      { name: 'Mike', email: 'mike@example.com' },
      { name: 'Sarah', email: 'sarah@example.com' },
    ],
  },
  {
    id: '5',
    sport: 'Tennis',
    location: 'Northwestern Tennis Courts',
    startTime: '2026-04-09T08:00',
    endTime: '2026-04-09T09:00',
    capacity: 2,
    organizer: 'emma@example.com',
    note: 'Singles match - first come, first serve.',
    skillLevel: 'Beginner',
    ageRange: '18+',
    gender: 'Any',
    requirements: 'Racket and balls provided.',
    players: [{ name: 'Emma', email: 'emma@example.com' }],
  },
  {
    id: '6',
    sport: 'Frisbee',
    location: 'Hutchson Field',
    startTime: '2026-04-09T14:00',
    endTime: '2026-04-09T15:30',
    capacity: 10,
    organizer: 'frank@example.com',
    note: 'Casual frisbee throwing and games.',
    skillLevel: 'Beginner',
    ageRange: '16+',
    gender: 'Mixed',
    requirements: 'Wear sunscreen.',
    players: [
      { name: 'Frank', email: 'frank@example.com' },
      { name: 'Grace', email: 'grace@example.com' },
    ],
  },
  {
    id: '7',
    sport: 'Soccer',
    location: 'Hutchson Field',
    startTime: '2026-04-10T18:30',
    endTime: '2026-04-10T20:00',
    capacity: 12,
    organizer: 'henry@example.com',
    note: 'Small-sided soccer for all levels.',
    skillLevel: 'Intermediate',
    ageRange: '18+',
    gender: 'Men',
    requirements: 'Bring water bottle.',
    players: [
      { name: 'Henry', email: 'henry@example.com' },
      { name: 'Ian', email: 'ian@example.com' },
    ],
  },
  {
    id: '8',
    sport: 'Tennis',
    location: 'Northwestern Tennis Courts',
    startTime: '2026-04-10T16:00',
    endTime: '2026-04-10T17:00',
    capacity: 4,
    organizer: 'isabella@example.com',
    note: 'Doubles tournament practice.',
    skillLevel: 'Advanced',
    ageRange: '20+',
    gender: 'Women',
    requirements: 'Bring your own racket.',
    players: [
      { name: 'Isabella', email: 'isabella@example.com' },
      { name: 'Julia', email: 'julia@example.com' },
    ],
  },
  {
    id: '9',
    sport: 'Frisbee',
    location: 'Deering Meadow',
    startTime: '2026-04-11T11:00',
    endTime: '2026-04-11T12:30',
    capacity: 8,
    organizer: 'jack@example.com',
    note: 'Ultimate frisbee training session.',
    skillLevel: 'Advanced',
    ageRange: '18-30',
    gender: 'Mixed',
    requirements: 'Athletic clothing and cleats.',
    players: [
      { name: 'Jack', email: 'jack@example.com' },
      { name: 'Kate', email: 'kate@example.com' },
      { name: 'Liam', email: 'liam@example.com' },
    ],
  },
  {
    id: '10',
    sport: 'Soccer',
    location: 'Hutchson Field',
    startTime: '2026-04-11T20:00',
    endTime: '2026-04-11T21:30',
    capacity: 14,
    organizer: 'lisa@example.com',
    note: 'Evening pickup game.',
    skillLevel: 'Beginner',
    ageRange: '16+',
    gender: 'Mixed',
    requirements: 'No cleats required.',
    players: [{ name: 'Lisa', email: 'lisa@example.com' }],
  },
  {
    id: '11',
    sport: 'Tennis',
    location: 'Northwestern Tennis Courts',
    startTime: '2026-04-12T10:00',
    endTime: '2026-04-12T11:00',
    capacity: 2,
    organizer: 'mark@example.com',
    note: 'Morning singles practice.',
    skillLevel: 'Intermediate',
    ageRange: '25+',
    gender: 'Any',
    requirements: 'Racket required.',
    players: [{ name: 'Mark', email: 'mark@example.com' }],
  },
  {
    id: '12',
    sport: 'Frisbee',
    location: 'Hutchson Field',
    startTime: '2026-04-12T15:00',
    endTime: '2026-04-12T16:30',
    capacity: 16,
    organizer: 'nina@example.com',
    note: 'Large group frisbee games.',
    skillLevel: 'Beginner',
    ageRange: '18+',
    gender: 'Mixed',
    requirements: 'Bring water.',
    players: [
      { name: 'Nina', email: 'nina@example.com' },
      { name: 'Oliver', email: 'oliver@example.com' },
      { name: 'Paula', email: 'paula@example.com' },
    ],
  },
  {
    id: '13',
    sport: 'Soccer',
    location: 'Hutchson Field',
    startTime: '2026-04-13T17:00',
    endTime: '2026-04-13T18:30',
    capacity: 10,
    organizer: 'quinn@example.com',
    note: 'Afternoon soccer session.',
    skillLevel: 'Intermediate',
    ageRange: '18-40',
    gender: 'Women',
    requirements: 'Comfortable shoes.',
    players: [
      { name: 'Quinn', email: 'quinn@example.com' },
      { name: 'Rachel', email: 'rachel@example.com' },
    ],
  },
  {
    id: '14',
    sport: 'Tennis',
    location: 'Northwestern Tennis Courts',
    startTime: '2026-04-13T14:00',
    endTime: '2026-04-13T15:00',
    capacity: 4,
    organizer: 'steve@example.com',
    note: 'Weekend doubles.',
    skillLevel: 'Beginner',
    ageRange: '18+',
    gender: 'Mixed',
    requirements: 'Rackets provided.',
    players: [
      { name: 'Steve', email: 'steve@example.com' },
      { name: 'Tina', email: 'tina@example.com' },
    ],
  },
  {
    id: '15',
    sport: 'Frisbee',
    location: 'Deering Meadow',
    startTime: '2026-04-14T09:00',
    endTime: '2026-04-14T10:30',
    capacity: 12,
    organizer: 'ursula@example.com',
    note: 'Morning frisbee fun.',
    skillLevel: 'Intermediate',
    ageRange: '16+',
    gender: 'Any',
    requirements: 'Wear hat and sunscreen.',
    players: [
      { name: 'Ursula', email: 'ursula@example.com' },
      { name: 'Victor', email: 'victor@example.com' },
    ],
  },
  {
    id: '16',
    sport: 'Soccer',
    location: 'Hutchson Field',
    startTime: '2026-04-14T19:30',
    endTime: '2026-04-14T21:00',
    capacity: 18,
    organizer: 'wendy@example.com',
    note: 'Large group soccer match.',
    skillLevel: 'Advanced',
    ageRange: '20+',
    gender: 'Mixed',
    requirements: 'Cleats and shin guards.',
    players: [
      { name: 'Wendy', email: 'wendy@example.com' },
      { name: 'Xavier', email: 'xavier@example.com' },
      { name: 'Yara', email: 'yara@example.com' },
    ],
  },
  {
    id: '17',
    sport: 'Tennis',
    location: 'Northwestern Tennis Courts',
    startTime: '2026-04-15T11:00',
    endTime: '2026-04-15T12:00',
    capacity: 4,
    organizer: 'zane@example.com',
    note: 'Mixed doubles tournament.',
    skillLevel: 'Intermediate',
    ageRange: '18+',
    gender: 'Mixed',
    requirements: 'Bring your own racket.',
    players: [
      { name: 'Zane', email: 'zane@example.com' },
      { name: 'Anna', email: 'anna@example.com' },
    ],
  },

  // ── Soccer ──────────────────────────────────────────────────
  {
    id: '18',
    sport: 'Soccer',
    location: 'Hutchson Field',
    startTime: '2026-04-13T19:00',
    endTime: '2026-04-13T20:30',
    capacity: 16,
    organizer: 'ben@example.com',
    note: 'Classic 8v8 — all levels welcome, just bring energy.',
    skillLevel: 'Beginner',
    ageRange: '18+',
    gender: 'Mixed',
    requirements: 'Wear athletic shoes.',
    players: [
      { name: 'Ben', email: 'ben@example.com' },
      { name: 'Chloe', email: 'chloe@example.com' },
    ],
  },
  {
    id: '19',
    sport: 'Soccer',
    location: 'Hutchson Field',
    startTime: '2026-04-14T18:00',
    endTime: '2026-04-14T19:30',
    capacity: 12,
    organizer: 'derek@example.com',
    note: 'Competitive 6v6, fast-paced play.',
    skillLevel: 'Advanced',
    ageRange: '20+',
    gender: 'Men',
    requirements: 'Cleats and shin guards required.',
    players: [
      { name: 'Derek', email: 'derek@example.com' },
      { name: 'Elena', email: 'elena@example.com' },
      { name: 'Finn', email: 'finn@example.com' },
      { name: 'Gina', email: 'gina@example.com' },
    ],
  },
  {
    id: '20',
    sport: 'Soccer',
    location: 'Hutchson Field',
    startTime: '2026-04-16T19:30',
    endTime: '2026-04-16T21:00',
    capacity: 14,
    organizer: 'hana@example.com',
    note: 'Relaxed Wednesday evening game — subs rotate every 10 min.',
    skillLevel: 'Intermediate',
    ageRange: '18-35',
    gender: 'Mixed',
    requirements: 'Bring water.',
    players: [{ name: 'Hana', email: 'hana@example.com' }],
  },
  {
    id: '21',
    sport: 'Soccer',
    location: 'Hutchson Field',
    startTime: '2026-04-18T18:00',
    endTime: '2026-04-18T19:30',
    capacity: 10,
    organizer: 'ivan@example.com',
    note: 'Women-only session — a safe and welcoming space to play.',
    skillLevel: 'Beginner',
    ageRange: '16+',
    gender: 'Women',
    requirements: 'No experience needed.',
    players: [
      { name: 'Ivan', email: 'ivan@example.com' },
      { name: 'Jade', email: 'jade@example.com' },
      { name: 'Karen', email: 'karen@example.com' },
    ],
  },
  {
    id: '22',
    sport: 'Soccer',
    location: 'Hutchson Field',
    startTime: '2026-04-19T20:00',
    endTime: '2026-04-19T21:30',
    capacity: 18,
    organizer: 'leo@example.com',
    note: 'Big Saturday night match — the more the merrier.',
    skillLevel: 'Intermediate',
    ageRange: '18+',
    gender: 'Mixed',
    requirements: 'Shin guards recommended.',
    players: [
      { name: 'Leo', email: 'leo@example.com' },
      { name: 'Mia', email: 'mia@example.com' },
      { name: 'Noah', email: 'noah@example.com' },
      { name: 'Olivia', email: 'olivia@example.com' },
      { name: 'Pete', email: 'pete@example.com' },
    ],
  },

  // ── Frisbee ─────────────────────────────────────────────────
  {
    id: '23',
    sport: 'Frisbee',
    location: 'Deering Meadow',
    startTime: '2026-04-13T16:00',
    endTime: '2026-04-13T17:30',
    capacity: 14,
    organizer: 'quinn@example.com',
    note: 'Casual Sunday toss — no experience needed, discs provided.',
    skillLevel: 'Beginner',
    ageRange: '16+',
    gender: 'Any',
    requirements: 'Wear comfortable shoes.',
    players: [
      { name: 'Quinn', email: 'quinn2@example.com' },
      { name: 'Rosa', email: 'rosa@example.com' },
    ],
  },
  {
    id: '24',
    sport: 'Frisbee',
    location: 'Hutchson Field',
    startTime: '2026-04-14T20:00',
    endTime: '2026-04-14T21:30',
    capacity: 16,
    organizer: 'sam2@example.com',
    note: 'Ultimate frisbee — 7v7 standard rules.',
    skillLevel: 'Intermediate',
    ageRange: '18+',
    gender: 'Mixed',
    requirements: 'Cleats helpful on the field.',
    players: [
      { name: 'Sam', email: 'sam2@example.com' },
      { name: 'Tara', email: 'tara@example.com' },
      { name: 'Uma', email: 'uma@example.com' },
    ],
  },
  {
    id: '25',
    sport: 'Frisbee',
    location: 'Deering Meadow',
    startTime: '2026-04-15T14:00',
    endTime: '2026-04-15T15:30',
    capacity: 10,
    organizer: 'val@example.com',
    note: 'Skills clinic + scrimmage. Great for people new to ultimate.',
    skillLevel: 'Beginner',
    ageRange: '16-25',
    gender: 'Mixed',
    requirements: 'Bring water and sunscreen.',
    players: [{ name: 'Val', email: 'val@example.com' }],
  },
  {
    id: '26',
    sport: 'Frisbee',
    location: 'Deering Meadow',
    startTime: '2026-04-17T17:00',
    endTime: '2026-04-17T18:30',
    capacity: 12,
    organizer: 'will@example.com',
    note: 'Competitive disc — bring your A-game.',
    skillLevel: 'Advanced',
    ageRange: '18-30',
    gender: 'Mixed',
    requirements: 'Experience with ultimate required.',
    players: [
      { name: 'Will', email: 'will@example.com' },
      { name: 'Xena', email: 'xena@example.com' },
      { name: 'Yusuf', email: 'yusuf@example.com' },
      { name: 'Zoe', email: 'zoe@example.com' },
    ],
  },
  {
    id: '27',
    sport: 'Frisbee',
    location: 'Hutchson Field',
    startTime: '2026-04-19T18:00',
    endTime: '2026-04-19T19:30',
    capacity: 20,
    organizer: 'alex2@example.com',
    note: 'Big pickup ultimate — open to everyone, we split teams on arrival.',
    skillLevel: 'Beginner',
    ageRange: '18+',
    gender: 'Mixed',
    requirements: 'Just show up!',
    players: [
      { name: 'Alex', email: 'alex2@example.com' },
      { name: 'Britt', email: 'britt@example.com' },
    ],
  },

  // ── Tennis ──────────────────────────────────────────────────
  {
    id: '28',
    sport: 'Tennis',
    location: 'Northwestern Tennis Courts',
    startTime: '2026-04-13T09:00',
    endTime: '2026-04-13T10:00',
    capacity: 4,
    organizer: 'carl@example.com',
    note: 'Doubles match — bring a partner or we can pair you up.',
    skillLevel: 'Beginner',
    ageRange: '18+',
    gender: 'Mixed',
    requirements: 'Racket required, balls provided.',
    players: [
      { name: 'Carl', email: 'carl@example.com' },
      { name: 'Dana', email: 'dana@example.com' },
    ],
  },
  {
    id: '29',
    sport: 'Tennis',
    location: 'Northwestern Tennis Courts',
    startTime: '2026-04-14T10:00',
    endTime: '2026-04-14T11:00',
    capacity: 2,
    organizer: 'eve@example.com',
    note: 'Singles — looking for a similarly-leveled opponent.',
    skillLevel: 'Intermediate',
    ageRange: '20+',
    gender: 'Women',
    requirements: 'Bring your own racket.',
    players: [{ name: 'Eve', email: 'eve@example.com' }],
  },
  {
    id: '30',
    sport: 'Tennis',
    location: 'Northwestern Tennis Courts',
    startTime: '2026-04-16T08:00',
    endTime: '2026-04-16T09:00',
    capacity: 4,
    organizer: 'felix@example.com',
    note: 'Early morning doubles — fresh courts, fresh air.',
    skillLevel: 'Advanced',
    ageRange: '25+',
    gender: 'Men',
    requirements: 'Bring racket and water.',
    players: [
      { name: 'Felix', email: 'felix@example.com' },
      { name: 'Grace2', email: 'grace2@example.com' },
      { name: 'Hugo', email: 'hugo@example.com' },
    ],
  },
  {
    id: '31',
    sport: 'Tennis',
    location: 'Northwestern Tennis Courts',
    startTime: '2026-04-17T15:00',
    endTime: '2026-04-17T16:00',
    capacity: 4,
    organizer: 'iris@example.com',
    note: 'Mixed doubles — casual and friendly atmosphere.',
    skillLevel: 'Beginner',
    ageRange: '18+',
    gender: 'Mixed',
    requirements: 'All gear provided.',
    players: [{ name: 'Iris', email: 'iris@example.com' }],
  },
  {
    id: '32',
    sport: 'Tennis',
    location: 'Northwestern Tennis Courts',
    startTime: '2026-04-20T11:00',
    endTime: '2026-04-20T12:00',
    capacity: 4,
    organizer: 'jake@example.com',
    note: 'Sunday tournament warm-up — doubles practice.',
    skillLevel: 'Intermediate',
    ageRange: '18-35',
    gender: 'Mixed',
    requirements: 'Bring your racket.',
    players: [
      { name: 'Jake', email: 'jake@example.com' },
      { name: 'Kim', email: 'kim@example.com' },
    ],
  },
];

export const emptyDraft: GameDraft = {
  sport: '',
  location: '',
  date: '',
  startTime: '',
  endTime: '',
  capacity: 10,
  organizer: '',
  note: '',
  skillLevel: 'Beginner',
  ageRange: '18+',
  gender: 'Any',
  requirements: '',
};

export const skillLevels: GameDraft['skillLevel'][] = [
  'Beginner',
  'Intermediate',
  'Advanced',
];

export const ageRanges: string[] = [
  '16+',
  '18+',
  '20+',
  '25+',
  '16-25',
  '18-30',
  '18-35',
  '18-40',
  '20-35',
];

export const genders: PickupGame['gender'][] = ['Any', 'Men', 'Women', 'Mixed'];
